USE [PWC_CTRDB]
GO

/****** Object:  Table [dbo].[TAMLA_STG_ACCOUNTS_BASE_KYC]    Script Date: 1/16/2018 11:47:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TAMLA_STG_ACCOUNTS_BASE_KYC](
	[SOURCE_SYSTEM] [varchar](5) NOT NULL,
	[EXTRACTION_DATE] [char](8) NOT NULL,
	[ACCOUNT_SOURCE_REF_ID] [varchar](32) NOT NULL,
	[ACCOUNT_SOURCE_UNIQUE_ID] [varchar](32) NOT NULL,
	[ACCOUNT_NAME] [varchar](100) NOT NULL,
	[CUSTOMER_SOURCE_UNIQUE_ID] [varchar](32) NOT NULL,
	[ACCOUNT_STATUS_CODE] [varchar](10) NOT NULL,
	[CREDIT_DEBIT_CODE] [varchar](10) NOT NULL,
	[CURRENCY_CODE] [varchar](3) NOT NULL,
	[DATE_OPENED] [char](8) NOT NULL,
	[DATE_CLOSED] [char](8) NULL,
	[LAST_UPDATED_TIMESTAMP] [varchar](26) NULL,
	[ACCOUNT_BALANCE] [numeric](18, 2) NULL,
	[OVERDRAFT_LIMIT] [decimal](18, 2) NULL,
	[PERIODIC_LOAN_AMOUNT] [numeric](18, 2) NULL,
	[LIFE_INS_CONTRACT_DURATION] [int] NULL,
	[BRANCH_ID] [varchar](32) NOT NULL,
	[RELATIONSHIP_MGR_ID] [varchar](32) NOT NULL,
	[IBAN] [varchar](28) NULL,
	[BIC] [varchar](11) NULL,
	[FROZEN_OVERRIDE_DATE] [char](8) NULL,
	[PRODUCT_SOURCE_TYPE_CODE] [varchar](20) NULL,
	[CREDIT_LIMIT] [decimal](18, 2) NULL,
	[RISK_SCORE] [numeric](18, 2) NULL,
	[ACCOUNT_SEGMENT] [varchar](30) NULL,
	[DORMANT_STATUS_FLAG] [char](1) NULL,
	[FROZEN_STATUS_FLAG] [char](1) NULL,
	[CREDIT_GRADE] [varchar](10) NULL,
	[REF_DEBT_COL_FLAG] [char](1) NULL,
	[BALANCE_DATE] [char](8) NULL,
	[COMMENTS] [varchar](4000) NULL,
	[ORG_UNIT_CODE] [varchar](10) NOT NULL,
	[ISSUE_DATE] [char](8) NULL,
	[PAYMENT_FREQ] [int] NULL,
	[INST_PREMIUM_AMT] [decimal](18, 2) NULL,
	[ANN_PREMIUM_AMT] [decimal](18, 2) NULL,
	[SINGLE_PREMIUM_TOTAL] [decimal](18, 2) NULL,
	[SUM_INSURED] [decimal](18, 2) NULL,
	[PAYMENT_METHOD] [varchar](50) NULL,
	[BENEFICIARY_FLAG] [char](1) NULL,
	[GROSS_PREM_TTD] [decimal](18, 2) NULL,
	[CASH_SURR_VALUE] [decimal](18, 2) NULL,
	[DEATH_BENEFIT_AMT] [decimal](18, 2) NULL,
	[CUSTOMER_INITIATED_CLOSURE] [char](1) NULL,
	[DELAYED_ACCOUNT_FLAG] [char](1) NULL,
	[LANGUAGE_PREF_CODE] [varchar](2) NULL,
	[SETTLEMENT_BANK_NAME] [varchar](80) NULL,
	[DELIVERY_INSTRUCTIONS] [varchar](150) NULL,
	[SETTLEMENT_TYPE] [varchar](10) NULL,
	[RISK_CATEGORY] [varchar](10) NULL,
	[BLOCKED_TYPE] [char](1) NULL,
	[BLOCKED_REASON] [varchar](37) NULL,
	[PRIMARY_CARD_ID] [varchar](20) NULL,
	[ADDRESS] [varchar](400) NULL,
	[ZONE] [varchar](100) NULL,
	[POSTAL_CODE] [varchar](20) NULL,
	[COUNTRY_CODE] [varchar](3) NULL,
	[CREDIT_TURNOVER] [decimal](18, 2) NULL,
	[DEBIT_TURNOVER] [decimal](18, 2) NULL,
	[TURNOVER_FROM_DATE] [char](8) NULL,
	[TURNOVER_TO_DATE] [char](8) NULL,
	[HOLDING_BANK_NAME] [varchar](80) NULL,
	[SALARY_LODGED_FLAG] [char](1) NULL,
	[ACCOUNT_ON_HOLD_FLAG] [char](1) NULL,
	[SENT_CORRESPONDENCE_FLAG] [char](1) NULL,
	[ACCOUNT_PURPOSE] [varchar](64) NULL,
	[DATA_INSRTED_DATE] [datetime] NOT NULL,
	[RECORD_CHANGE_TYPE] [varchar](10) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


