select REPLACE(LTRIM(REPLACE('00000123fa001', '0', ' ')), ' ', '0') --- Remove Leading 0 for Registration_number
select RIGHT('00000' + CONVERT(nvarchar, 2),5) --- Leading 0 for Banch code
select CAST(43034 - 2 as datetime) --- convert to date

select * from [dbo].[CHK_SRC_PARAMETERS]

---- INSERT EDW ---
insert into [dbo].[CHK_SRC_PARAMETERS] (
	[SRC_SYSTEM],
	[REGISTER_NAME], 
	[REGISTER_NUMBER], 
	[REGISTER_OFFICE_ADDRESS],
	[NATURE_OF_BUSINESS],
	[INDIVIDUAL_NAME_AP],
	[INDIVIDUAL_NRIC_AP],
	[LAST_MAINTENANCE_DATE]
)
select 'EDW' as SRC_SYSTEM, 
	[Registered name], 
	REPLACE(LTRIM(REPLACE([Business registration number], '0', ' ')), ' ', '0') as REGISTER_NUMBER,
	[Registered Office Address],
	[Nature of business (listing)],
	[Individual Name],
	[Individual NRIC / Passport Number],
	[Last maintenance date]
from [dbo].[STAGE_EDW]


---- Insert EDW part3 
--select * from [dbo].[LOOKUP_BUSINESS_TYPE]

insert into [dbo].[CHK_SRC_PARAMETERS] (
	SRC_SYSTEM,
	REGISTER_NAME,
	REGISTER_NUMBER,
	NATURE_OF_BUSINESS,
	REGISTER_OFFICE_ADDRESS,
	LAST_MAINTENANCE_DATE,
	INDIVIDUAL_NRIC_BO,
	INDIVIDUAL_NAME_AP
)
select 
	'EDW' as SRC_SYSTEM,
	CO_NM,
	REPLACE(LTRIM(REPLACE(CO_RGS_NUM, '0', ' ')), ' ', '0') as REGISTER_NUMBER,
	b.BUSINESS_TYPE_DESC,
	ADR,
	CST_RCRD_LST_MOD_DT,
	CST_SRC_UNQ_ID,
	SGNY_NM
from [dbo].[STAGE_EDW_Part3] a 
LEFT JOIN [dbo].[LOOKUP_BUSINESS_TYPE] b ON REPLACE(LTRIM(REPLACE(a.BNM_IDY_CD, '0', ' ')), ' ', '0') = b.SOURCESYS_VALUE
where b.SOURCE_SYSTEM = 'EDW'

----- Insert TIPLIS 
insert into [dbo].[CHK_SRC_PARAMETERS] (
	[SRC_SYSTEM],
	[REGISTER_NAME],
	[REGISTER_NUMBER],
	[REGISTER_OFFICE_ADDRESS],
	[NATURE_OF_BUSINESS],
	[BRANCH_CODE]
)
select 'TiPLIS' as SCR_SYSTEM,
	[Registered name],
	REPLACE(LTRIM(REPLACE([Business registration number], '0', ' ')), ' ', '0') as REGISTER_NUMBER,
	CONCAT( [Address line 1], ' ', [Address line 2], ' ', [Address line 3], ' ', [Address line 4]) AS REGISTER_OFFICE_ADDRESS,
	[Nature of business desc],
	CASE WHEN (RIGHT('00000' + CONVERT(nvarchar, [Branch Code]),5)) = '00000' THEN NULL
		ELSE RIGHT('00000' + CONVERT(nvarchar, [Branch Code]),5)
	END  AS BRANCH_CODE
from [dbo].[STAGE_TiPLIS]

------ insert CLS 
insert into [dbo].[CHK_SRC_PARAMETERS] (
	[SRC_SYSTEM],
	[REGISTER_NAME],
	[REGISTER_NUMBER],
	[REGISTER_OFFICE_ADDRESS],
	[NATURE_OF_BUSINESS],
	[LAST_MAINTENANCE_DATE],
	[BRANCH_CODE]
)
SELECT 'CLS' as SRC_SYSTEM,
	[Registered name],
	REPLACE(LTRIM(REPLACE([Business registration number], '0', ' ')), ' ', '0') as REGISTER_NUMBER,
	CONCAT( [Address line 1], ' ', [Address line 2], ' ', [Address line 3], ' ', [Address line 4]) AS REGISTER_OFFICE_ADDRESS,
	[Nature of business desc],
	CASE WHEN [Last maintenance date] = 0 THEN NULL
		ELSE '20'+ CONVERT(NVARCHAR, CAST([Last maintenance date] - 2 as datetime), 12)
	END AS LAST_MAINTENANCE_DATE,
	CASE WHEN (RIGHT('00000' + CONVERT(nvarchar, [Branch Code]),5)) = '00000' THEN NULL
		ELSE RIGHT('00000' + CONVERT(nvarchar, [Branch Code]),5)
	END  AS BRANCH_CODE
FROM [dbo].[STAGE_CLS]

---- insert RDW 
insert into [dbo].[CHK_SRC_PARAMETERS](
	SRC_SYSTEM,
	REGISTER_NAME,
	REGISTER_NUMBER,
	REGISTER_OFFICE_ADDRESS,
	LAST_MAINTENANCE_DATE
)
select 'RDW' as SRC_SYSTEM,
	CUS_NM_LINE,
	REPLACE(LTRIM(REPLACE([CUS_PRIMARY_ID], '0', ' ')), ' ', '0') as REGISTER_NUMBER,
	CONCAT( [CUS_ADDR_1], ' ', [CUS_ADDR_2], ' ', [CUS_ADDR_3], ' ', [CUS_ADDR_4]) AS REGISTER_OFFICE_ADDRESS,
	[CUS_LST_MAINT_DT]
from [dbo].[STAGE_RDW]


------------------------ JOIN with high risk customer ------
----- Stat ---- 
select count(distinct REGISTER_NUMBER) from [dbo].[CHK_SRC_PARAMETERS] --- 14846
select count(1) from [dbo].[STAGE_IND_HR] a JOIN [dbo].[CHK_SRC_PARAMETERS] b 
ON a.CUSTOMER_ID = b.REGISTER_NUMBER --- 13864
select count(distinct customer_id) from [dbo].[STAGE_IND_HR] --- 14857
select count(*) from [dbo].[STAGE_CLS]
select count(*) from [dbo].[STAGE_EDW]
select count(*) from [dbo].[STAGE_EDW_Part3]
select count(*) from [dbo].[STAGE_RDW]
select count(*) from [dbo].[STAGE_TiPLIS]
select count(*) from [dbo].[STAGE_IND_HR]
----- All result detail ---- 
select
	a.CUSTOMER_ID,
	CASE WHEN b.[SRC_SYSTEM] is NULL THEN 'NOT FOUND' ELSE b.[SRC_SYSTEM] END AS "SRC_SYSTEM",
	b.[REGISTER_NAME],
	b.[REGISTER_NUMBER],
	b.[REGISTER_OFFICE_ADDRESS],
	b.[PRINCIPAL_BUSINESS_ADDRESS],
	b.[NATURE_OF_BUSINESS],
	b.[OWNERSHIP_STRUCTURE],
	b.[TYPE_BENEFICIAL_OWNER],
	b.[DESIGNATION_BO],
	b.[PERCENT_SHAREHOLDING_BO],
	b.[INDIVIDUAL_NRIC_BO],
	b.[MAILING_BO],
	b.[INDIVIDUAL_NAME_AP],
	b.[DESIGNATION_AP],
	b.[INDIVIDUAL_NRIC_AP],
	b.[MAILING_AP],
	b.[INDIVIDUAL_NAME_SM],
	b.[DESIGNATION_SM],
	b.[INDIVIDUAL_NRIC_SM],
	b.[MAILING_SM],
	b.[PURPOSE_OF_ACCOUNT],
	b.[INFO_SRC_WEALTH_NET_WORTH],
	b.[INFO_SRC_FUND],
	b.[TRANSACTION_CODES],
	b.[LAST_MAINTENANCE_DATE],
	b.[SPB_SIGNATURE_PRIOR_BANKING],
	b.[BRANCH_CODE],
	b.[BUSINESS_REGISTRATION_SUP_DOC],
	b.[ULTIMATE_OWNER_SUP_DOC],
	b.[BORROWING_CUSTOMER_LC_MEMO],
	b.[LAST_ACCOUNT_REVIEW_DATE]
into #temp_a
from [dbo].[STAGE_IND_HR] a LEFT JOIN
[dbo].[CHK_SRC_PARAMETERS] b ON a.CUSTOMER_ID = b.REGISTER_NUMBER
ORDER BY b.SRC_SYSTEM DESC

select CUSTOMER_ID, 
     CASE WHEN MAX([SRC_SYSTEM]) is NULL THEN '0' ELSE '1' END AS [SRC_SYSTEM],
     CASE WHEN MAX([REGISTER_NAME]) is NULL THEN '0' ELSE '1' END AS [REGISTER_NAME],
     CASE WHEN MAX([REGISTER_NUMBER]) is NULL THEN '0' ELSE '1' END AS [REGISTER_NUMBER],
     CASE WHEN MAX([REGISTER_OFFICE_ADDRESS]) is NULL THEN '0' ELSE '1' END AS [REGISTER_OFFICE_ADDRESS],
     CASE WHEN MAX([PRINCIPAL_BUSINESS_ADDRESS]) is NULL THEN '0' ELSE '1' END AS [PRINCIPAL_BUSINESS_ADDRESS],
     CASE WHEN MAX([NATURE_OF_BUSINESS]) is NULL THEN '0' ELSE '1' END AS [NATURE_OF_BUSINESS],
     CASE WHEN MAX([OWNERSHIP_STRUCTURE]) is NULL THEN '0' ELSE '1' END AS [OWNERSHIP_STRUCTURE],
     CASE WHEN MAX([TYPE_BENEFICIAL_OWNER]) is NULL THEN '0' ELSE '1' END AS [TYPE_BENEFICIAL_OWNER],
     CASE WHEN MAX([DESIGNATION_BO]) is NULL THEN '0' ELSE '1' END AS [DESIGNATION_BO],
     CASE WHEN MAX([PERCENT_SHAREHOLDING_BO]) is NULL THEN '0' ELSE '1' END AS [PERCENT_SHAREHOLDING_BO],
     CASE WHEN MAX([INDIVIDUAL_NRIC_BO]) is NULL THEN '0' ELSE '1' END AS [INDIVIDUAL_NRIC_BO],
     CASE WHEN MAX([MAILING_BO]) is NULL THEN '0' ELSE '1' END AS [MAILING_BO],
     CASE WHEN MAX([INDIVIDUAL_NAME_AP]) is NULL THEN '0' ELSE '1' END AS [INDIVIDUAL_NAME_AP],
     CASE WHEN MAX([DESIGNATION_AP]) is NULL THEN '0' ELSE '1' END AS [DESIGNATION_AP],
     CASE WHEN MAX([INDIVIDUAL_NRIC_AP]) is NULL THEN '0' ELSE '1' END AS [INDIVIDUAL_NRIC_AP],
     CASE WHEN MAX([MAILING_AP]) is NULL THEN '0' ELSE '1' END AS [MAILING_AP],
     CASE WHEN MAX([INDIVIDUAL_NAME_SM]) is NULL THEN '0' ELSE '1' END AS [INDIVIDUAL_NAME_SM],
     CASE WHEN MAX([DESIGNATION_SM]) is NULL THEN '0' ELSE '1' END AS [DESIGNATION_SM],
     CASE WHEN MAX([INDIVIDUAL_NRIC_SM]) is NULL THEN '0' ELSE '1' END AS [INDIVIDUAL_NRIC_SM],
     CASE WHEN MAX([MAILING_SM]) is NULL THEN '0' ELSE '1' END AS [MAILING_SM],
     CASE WHEN MAX([PURPOSE_OF_ACCOUNT]) is NULL THEN '0' ELSE '1' END AS [PURPOSE_OF_ACCOUNT],
     CASE WHEN MAX([INFO_SRC_WEALTH_NET_WORTH]) is NULL THEN '0' ELSE '1' END AS [INFO_SRC_WEALTH_NET_WORTH],
     CASE WHEN MAX([INFO_SRC_FUND]) is NULL THEN '0' ELSE '1' END AS [INFO_SRC_FUND],
     CASE WHEN MAX([TRANSACTION_CODES]) is NULL THEN '0' ELSE '1' END AS [TRANSACTION_CODES],
     CASE WHEN MAX([LAST_MAINTENANCE_DATE]) is NULL THEN '0' ELSE '1' END AS [LAST_MAINTENANCE_DATE],
     CASE WHEN MAX([SPB_SIGNATURE_PRIOR_BANKING]) is NULL THEN '0' ELSE '1' END AS [SPB_SIGNATURE_PRIOR_BANKING],
     CASE WHEN MAX([BRANCH_CODE]) is NULL THEN '0' ELSE '1' END AS [BRANCH_CODE],
     CASE WHEN MAX([BUSINESS_REGISTRATION_SUP_DOC]) is NULL THEN '0' ELSE '1' END AS [BUSINESS_REGISTRATION_SUP_DOC],
     CASE WHEN MAX([ULTIMATE_OWNER_SUP_DOC]) is NULL THEN '0' ELSE '1' END AS [ULTIMATE_OWNER_SUP_DOC],
     CASE WHEN MAX([BORROWING_CUSTOMER_LC_MEMO]) is NULL THEN '0' ELSE '1' END AS [BORROWING_CUSTOMER_LC_MEMO],
     CASE WHEN MAX([LAST_ACCOUNT_REVIEW_DATE]) is NULL THEN '0' ELSE '1' END AS [LAST_ACCOUNT_REVIEW_DATE]
from #temp_a 
GROUP BY CUSTOMER_ID
ORDER BY CUSTOMER_ID
